<a href="https://colab.research.google.com/github/np03cs4a240275-eng/Fullstack-development-240275/blob/main/worksheet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 1. Initialize an empty array with size 2x2.
empty_2x2 = np.empty((2, 2))
print(empty_2x2)

[[1.14485233e-315 0.00000000e+000]
 [1.25990592e-300 1.39067116e-309]]


In [ ]:
# 2. Initialize an all one array with size 4x2.
ones_4x2 = np.ones((4, 2))
print(ones_4x2)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# 3. Return a new array of given shape and type, filled with fill value.
full_array = np.full((3, 3), 7)
print(full_array)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
# 4. Return a new array of zeros with same shape and type as a given array.
given_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_given = np.zeros_like(given_array)
print(given_array_zeros)

[[0 0 0]
 [0 0 0]]


In [5]:
# 5. Create a 10x10 array with random values and find the minimum and maximum values.
rand_10x10 = np.random.random((10, 10))
rand_10x10_min = rand_10x10.min()
rand_10x10_max = rand_10x10.max()
print(rand_10x10)
print("Min:", rand_10x10_min)
print("Max:", rand_10x10_max)

[[0.81815398 0.82559106 0.54584664 0.19888153 0.23676084 0.85982345
  0.90600166 0.37696076 0.69084208 0.38263955]
 [0.8990015  0.65291046 0.35247542 0.98784582 0.64681141 0.69498626
  0.21381447 0.92854076 0.41213674 0.53372348]
 [0.97972519 0.08444904 0.06403776 0.00751331 0.19454489 0.08825601
  0.19288651 0.22409051 0.10524651 0.0024176 ]
 [0.04848283 0.43279407 0.9919437  0.85381357 0.27927504 0.91101192
  0.85810279 0.89413479 0.71762567 0.88032313]
 [0.70886865 0.56286836 0.88035698 0.6268711  0.12902462 0.92232495
  0.35544637 0.78535578 0.45826195 0.68772583]
 [0.77140222 0.23687419 0.54099642 0.43992218 0.53908628 0.16705245
  0.84549027 0.99687569 0.26801765 0.84644952]
 [0.08283729 0.46551849 0.44747095 0.48228789 0.84814258 0.9393365
  0.59812485 0.17489402 0.88945663 0.73982447]
 [0.91850994 0.18906431 0.14018034 0.05901329 0.93351923 0.75788044
  0.75600333 0.19662254 0.29453141 0.75247999]
 [0.63332388 0.75167419 0.06402683 0.63120106 0.54853335 0.4535096
  0.09631019 0

In [6]:
# 6. For an existing list new_list = [1,2,3,4] convert to a numpy array.
new_list = [1, 2, 3, 4]
np_array_from_list = np.array(new_list)
print(np_array_from_list)

[1 2 3 4]


In [7]:

# 2.1. Create an array with values ranging from 10 to 49.
arr_10_49 = np.arange(10, 50)
print(arr_10_49)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
# 2.2. Create a 3x3 matrix with values ranging from 0 to 8.
matrix_0_8 = np.arange(9).reshape(3, 3)
print(matrix_0_8)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
# 2.3. Create a 3x3 identity matrix.
identity_3x3 = np.eye(3)
print(identity_3x3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
# 2.4. Create a random array of size 30 and find the mean of the array.
rand_30 = np.random.random(30)
rand_30_mean = rand_30.mean()
print(rand_30)
print("Mean:", rand_30_mean)

[0.13386946 0.1117422  0.59950179 0.05766822 0.46216964 0.41932588
 0.15864197 0.49113555 0.25183119 0.54420556 0.88622118 0.08089743
 0.22663703 0.75848582 0.50009132 0.10193946 0.12219775 0.904384
 0.34120629 0.74270305 0.0994696  0.25351642 0.60408668 0.14131615
 0.1042772  0.3898868  0.35637789 0.81602288 0.52630186 0.40007741]
Mean: 0.38620625659560953


In [12]:
# 2.5. Create a 10x10 array with random values and find the minimum and maximum values.
rand_10x10 = np.random.random((10, 10))
rand_10x10_min = rand_10x10.min()
rand_10x10_max = rand_10x10.max()
print(rand_10x10)
print("Min:", rand_10x10_min)
print("Max:", rand_10x10_max)

[[0.8329102  0.01463416 0.24999689 0.38172519 0.0069907  0.47695746
  0.35997027 0.85996671 0.87057147 0.21949814]
 [0.58735959 0.99018092 0.02987955 0.74993346 0.79659609 0.14616706
  0.12563008 0.89120236 0.4752084  0.54753236]
 [0.60305186 0.69766074 0.61671296 0.76706688 0.08700658 0.99375454
  0.61280464 0.2478896  0.96044393 0.23911144]
 [0.81254069 0.89774723 0.83624226 0.01178231 0.32222821 0.58841656
  0.366643   0.28432623 0.55176802 0.18175999]
 [0.95387868 0.08491366 0.54372299 0.67779166 0.80873032 0.31445618
  0.72010782 0.9940002  0.17270508 0.74710198]
 [0.5156963  0.9806405  0.8498212  0.14036745 0.39162527 0.22791151
  0.11263838 0.01327436 0.28621393 0.07311272]
 [0.75967901 0.15824948 0.87677629 0.1071932  0.45553451 0.19913146
  0.57563869 0.98817388 0.72952995 0.91560359]
 [0.12126641 0.97193839 0.09428538 0.20163667 0.05665404 0.50353892
  0.36456338 0.32928728 0.37513722 0.90865559]
 [0.74574635 0.67769911 0.67702235 0.7097156  0.06192509 0.88700473
  0.87194811

In [13]:

# 2.6. Create a zero array of size 10 and replace 5th element with 1.
zeros_10 = np.zeros(10)
zeros_10[4] = 1
print(zeros_10)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [14]:
# 2.7. Reverse an array arr = [1,2,0,0,4,0].
arr = np.array([1, 2, 0, 0, 4, 0])
arr_reversed = arr[::-1]
print(arr_reversed)

[0 4 0 0 2 1]


In [15]:
# 2.8. Create a 2d array with 1 on border and 0 inside.
border_1_inside_0 = np.ones((5, 5), dtype=int)
border_1_inside_0[1:-1, 1:-1] = 0
print(border_1_inside_0)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [16]:
# 2.9. Create an 8x8 matrix and fill it with a checkerboard pattern.
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[::2, 1::2] = 1
checkerboard[1::2, ::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [17]:

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 3.1. Add the two array.
add_xy = x + y
print(add_xy)

[[ 6  8]
 [10 13]]


In [18]:
# 3.2. Subtract the two array.
sub_xy = x - y
print(sub_xy)

[[-4 -4]
 [-4 -3]]


In [19]:
# 3.3. Multiply the array with any integers of your choice.
x_times_3 = x * 3
print(x_times_3)

[[ 3  6]
 [ 9 15]]


In [20]:
# 3.4. Find the square of each element of the array.
x_squared = x ** 2
print(x_squared)

[[ 1  4]
 [ 9 25]]


In [22]:
# 3.5. Find the dot product between: v and w ; x and v ; x and y.
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("v * w:", dot_vw)
print("x * v:", dot_xv)
print("x * y:", dot_xy)

v * w: 219
x * v: [29 77]
x * y: [[19 22]
 [50 58]]


In [25]:
# 3.6. Concatenate x and y along row and concatenate v and w along column.
concat_xy_rows = np.concatenate((x, y), axis=0)
concat_vw_cols = np.column_stack((v, w))
print("Concatenate x and y along rows:")
print(concat_xy_rows)
print("Concatenate v and w along columns:")
print(concat_vw_cols)

Concatenate x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
[[ 9 11]
 [10 12]]


In [30]:
import numpy as np

A = np.array([[3, 4],
              [7, 8]])
B = np.array([[5, 3],
              [2, 1]])

A_inv = np.linalg.inv(A)
AA_inv = np.matmul(A, A_inv)
print("A * A^{-1} =\n", AA_inv)

AB = np.dot(A, B)
BA = np.dot(B, A)

print("\nAB =\n", AB)
print("\nBA =\n", BA)
print("\nIs AB equal to BA? ->", np.allclose(AB, BA))

AB_T = AB.T
BT_AT = np.dot(B.T, A.T)

print("\n(AB)^T =\n", AB_T)
print("\nB^T A^T =\n", BT_AT)
print("\nIs (AB)^T equal to B^T A^T? ->", np.allclose(AB_T, BT_AT))

A_sys = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3,  1, -1]])
b_sys = np.array([-1, -3, 9])

solution_solve = np.linalg.solve(A_sys, b_sys)
A_sys_inv = np.linalg.inv(A_sys)
solution_inv = np.dot(A_sys_inv, b_sys)

print("\nSolution using np.linalg.solve:\n", solution_solve)
print("\nSolution using inverse A^{-1}B:\n", solution_inv)
print("\nAre both solutions equal? ->", np.allclose(solution_solve, solution_inv))


A * A^{-1} =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB =
 [[23 13]
 [51 29]]

BA =
 [[36 44]
 [13 16]]

Is AB equal to BA? -> False

(AB)^T =
 [[23 51]
 [13 29]]

B^T A^T =
 [[23 51]
 [13 29]]

Is (AB)^T equal to B^T A^T? -> True

Solution using np.linalg.solve:
 [ 2.  1. -2.]

Solution using inverse A^{-1}B:
 [ 2.  1. -2.]

Are both solutions equal? -> True


In [29]:
import time

# Helper sizes
N = 1_000_000
M = 1000

# 4.2.1. Element-wise Addition
# Python lists
list_a = list(range(N))
list_b = list(range(N))

start = time.time()
list_add = [list_a[i] + list_b[i] for i in range(N)]
end = time.time()
time_list_add = end - start

# NumPy arrays
arr_a = np.arange(N)
arr_b = np.arange(N)

start = time.time()
arr_add = arr_a + arr_b
end = time.time()
time_numpy_add = end - start

print("Element-wise addition - Python lists time:", time_list_add)
print("Element-wise addition - NumPy arrays time:", time_numpy_add)

# 4.2.2. Element-wise Multiplication
# Python lists
start = time.time()
list_mul = [list_a[i] * list_b[i] for i in range(N)]
end = time.time()
time_list_mul = end - start

# NumPy arrays
start = time.time()
arr_mul = arr_a * arr_b
end = time.time()
time_numpy_mul = end - start

print("Element-wise multiplication - Python lists time:", time_list_mul)
print("Element-wise multiplication - NumPy arrays time:", time_numpy_mul)

# 4.2.3. Dot Product
# Python lists
start = time.time()
dot_list = sum(list_a[i] * list_b[i] for i in range(N))
end = time.time()
time_list_dot = end - start

# NumPy arrays
start = time.time()
dot_numpy = np.dot(arr_a, arr_b)
end = time.time()
time_numpy_dot = end - start

print("Dot product - Python lists time:", time_list_dot)
print("Dot product - NumPy arrays time:", time_numpy_dot)

# 4.2.4. Matrix Multiplication
# Python lists
matrix_A_list = [[1.0] * M for _ in range(M)]
matrix_B_list = [[1.0] * M for _ in range(M)]

start = time.time()
matrix_C_list = [[sum(matrix_A_list[i][k] * matrix_B_list[k][j] for k in range(M))
                  for j in range(M)]
                 for i in range(M)]
end = time.time()
time_list_matmul = end - start

# NumPy arrays
matrix_A_np = np.ones((M, M))
matrix_B_np = np.ones((M, M))

start = time.time()
matrix_C_np = np.dot(matrix_A_np, matrix_B_np)
end = time.time()
time_numpy_matmul = end - start

print("Matrix multiplication (1000x1000) - Python lists time:", time_list_matmul)
print("Matrix multiplication (1000x1000) - NumPy arrays time:", time_numpy_matmul)


Element-wise addition - Python lists time: 0.1878204345703125
Element-wise addition - NumPy arrays time: 0.005561351776123047
Element-wise multiplication - Python lists time: 0.20298099517822266
Element-wise multiplication - NumPy arrays time: 0.005835771560668945
Dot product - Python lists time: 0.21415495872497559
Dot product - NumPy arrays time: 0.0023555755615234375
Matrix multiplication (1000x1000) - Python lists time: 129.25290751457214
Matrix multiplication (1000x1000) - NumPy arrays time: 0.07268476486206055
